apiVersion: v1
kind: Pod
metadata:
  name: alpine-dig
spec:
  containers:
    - name: alpine-dig
      image: srtlkn/alpine-dig:v1.0.0
      command:
        - sh
        - -c
        - "exec tail -f /dev/null"